### ISSUE TITLE
Installation instructions are problematic

### ISSUE THREAD

**Issue by najamelan** [int3h/sublime-better-javascript#1]
When following the installation instructions given in the readme, one runs into a couple of problems.
1. Git will refuse to clone because the JavaScript directory already exists and it is not empty.
2. It's not clear if you just need to overwrite the files with versions coming from this repo or if you should just replace your old Javascript directory with this repo.
3. If you start manipulating the folders while sublime is open you will get a bunch of warning dialogs because it can't read the files anymore.

Proposition:
1. Clone this repo somewhere on your system
2. Browse to your ST packages folder (Preferences->Browse Packages)
3. Close ST
4. Copy everything but LICENSE and README.md from this repository  and overwrite the files in your packages folder/JavaScript
5. Start ST and enjoy

If it didn't work, try closing all javascript files and restarting sublime.

---

Other than that, it works! Thanks alot. Goto Symbol is no longer completely useless. Still hoping for a proper outliner someday.

**Comment by int3h** [comment]
Hmm, this is a good point. In ST3, all the pristine packages are held ZIPed in Sublime's app directory, and so the 'JavaScript' folder never exists unless you create it. In ST2, Sublime automatically copies all of its default packages into the user package directory in unzipped form.

I'll modify the instructions to reflect this. 

The real solution is to find a way to have this coexist with the existing JS package, without the need to overwrite it. I wonder if I just created a plugin that was a full install of the modified JS package under a different name, and had a plugin that would deactivate the regular "JavaScript" plugin on load...
