### ISSUE TITLE
uninstall problem

### ISSUE THREAD

**Issue by tborychowski** [int3h/sublime-better-javascript#2]
After I uninstalled this package I'm getting an error:
![2013-08-15_153401](https://f.cloud.github.com/assets/392513/969132/bf49dffc-05b7-11e3-801b-bb8320f8e945.png)

and there's no syntax highlighting for js...

**Comment by int3h** [comment]
Did you read the uninstall instructions in the release notes that pop-up when you install the package?

**Comment by tborychowski** [comment]
I installed this using git-clone and there was no popup.
But I managed to resolve my issue:
- I removed "cache" and "index" folders 
- I removed "JavaScript" from ignored packages in user settings

**Comment by int3h** [comment]
That's a good point; that message is only displayed when this package is installed via Package Control. I'll add a note about uninstallation to the README.md.

The solution lies in removing "JavaScript" from the ignored packages setting. I wish there were a more elegant way to do this, but I wasn't able to find one.
