### ISSUE TITLE
Missing JavaScript.tmLanguage in Sublime 3

### ISSUE THREAD

**Issue by wvankuipers** [int3h/sublime-better-javascript#5]
When installing the plugin in Sublime 3 (on OSX) I received the following message on opening Sublime:

```
Error loading syntax file "Packages/Better JavaScript.sublime-package/JavaScript.tmLanguage": Unable to open Packages/Better JavaScript.sublime-package/JavaScript.tmLanguage
```

Since there is no dir `Better JavaScript.sublime-package` creating a symlink to `Better JavaScript` fixes this issue. ( `ln -s 'Better JavaScript'/ 'Better JavaScript.sublime-package'`  )

**Comment by ghost** [comment]
I had the same issue. After you remove the Better JavaScript package from sublime, go to 
Sublime Text --> Preferences --> Settings-user ---> look for "ignored_packages"  and you will see sublime ignored Javascript. Just delete "Javascript" within the "ignored_packages" then you should be fine.

**Comment by iandanforth** [comment]
@isliliye Thanks!

**Comment by foria** [comment]
+1

**Comment by yupire** [comment]
thanks @isliliye  !!!!

**Comment by Wndrr** [comment]
Thanks a lot @isliliye ! Pretty sure you saved me a ton of time here :-)

**Comment by deot** [comment]
+1

**Comment by Codedecks** [comment]
Thanks isliliye!

**Comment by Grakha** [comment]
@isliliye Awesome. Thanks.
