### ISSUE TITLE
Corrupts sublime javascript support

### ISSUE THREAD

**Issue by xsleonard** [int3h/sublime-better-javascript#7]
Installing this package resulted in several tmPreferences popup errors.  Instructions were followed to close all js files and delete the cache.  The tmPreferences errors went away upon restart but js was not highlighted.

Removing the package did not restore the original javascript functionality; javascript support is gone.  Its not a syntax option.   Creating a fresh data directory and copying the javascript cache files from that did not restore it.

**Comment by int3h** [comment]
Just change the syntax of the files to "Better JavaScript". You can re-enanle ST3's JS syntax by changing your settings.
