### ISSUE TITLE
Uninstalling causes error and breaks javascript

### ISSUE THREAD

**Issue by granteagon** [int3h/sublime-better-javascript#9]
Says package is missing.  Enabling javascript does not fix the issue.  I get two alerts saying:

> Error loading syntax file "Packages/Better JavaScript.sublime-package/JavaScript.tmLanguage": Unable to open Packages/Better JavaScript.sublime-package/JavaScript.tmLanguage

I uninstalled because of a similar error from SublimeREPL saying:

> Error loading syntax file "Packages/JavaScript/JavaScript.tmLanguage": Unable to open Packages/JavaScript/JavaScript.tmLanguage

This makes me a sad panda. :panda_face:

**Comment by granteagon** [comment]
Found uninstall instructions.

**Comment by KKrisu** [comment]
For anyone who is looking for the solution:
In my case I had to close all .js and .json files and restart sublime.

**Comment by douglaswebdesigns** [comment]
KKrisu your answer is exactly dead on. I had a js file open and tried everything I could to kill this error. Found your thread answer and it addressed the problem instantly.
